import SwiftUI
import SwiftData
struct ContentView:View{
 @Environment(\.modelContext) private var context
 @StateObject private var detector=AudioDetector();@StateObject private var game=GameController()
 @Query(sort:\SessionRecord.startedAt,order:.reverse) private var sessions:[SessionRecord]
 @State private var tab=0;@State private var error:String?
 var body:some View{TabView(selection:$tab){play.tag(0).tabItem{Label("Play",systemImage:"waveform")};calibrate.tag(1).tabItem{Label("Calibrate",systemImage:"tuningfork")};history.tag(2).tabItem{Label("History",systemImage:"clock")}}.task{detector.onHit={_ in game.hit(context:context)}}.alert("Microphone",isPresented:Binding(get:{error != nil},set:{if !$0{error=nil}})){Button("OK"){}}message:{Text(error ?? "")}}
 var play:some View{NavigationStack{VStack(spacing:24){Spacer();Text(game.active ? "CURRENT RALLY":"READY").font(.headline).foregroundStyle(.secondary);Text("\(game.currentHits)").font(.system(size:110,weight:.bold,design:.rounded));if game.active{Text("Saves after 3 seconds without a recognised hit").foregroundStyle(.secondary);ProgressView(value:Double(detector.lastConfidence));Text("Last sound confidence \(Int(detector.lastConfidence*100))%").font(.caption)};Spacer();Button(game.active ? "Finish Session":"Start Session"){Task{if game.active{game.stop(context:context);detector.stop()}else{guard (CalibrationStore.shared.profile?.count ?? 0)>=5 else{tab=1;return};do{try await detector.start();game.startSession(context:context)}catch{self.error=error.localizedDescription}}}}.buttonStyle(.borderedProminent).controlSize(.large);if game.active{Button("Add hit manually"){game.hit(context:context)}}}.padding().navigationTitle("PaddleCounter")}}
 var calibrate:some View{NavigationStack{VStack(spacing:22){Text("Teach your paddle sound").font(.title2.bold());Text("Put the phone where it will sit during play, then make 10–20 normal paddle hits with a short pause between them.").multilineTextAlignment(.center).foregroundStyle(.secondary);Text("\(detector.calibrationHits)").font(.system(size:72,weight:.bold,design:.rounded));Text("examples learned").foregroundStyle(.secondary);Button(detector.isRunning && detector.calibrationMode ? "Stop learning":"Learn hits"){Task{if detector.isRunning{detector.stop();detector.calibrationMode=false}else{detector.calibrationMode=true;do{try await detector.start()}catch{self.error=error.localizedDescription}}}}.buttonStyle(.borderedProminent);Button("Reset calibration",role:.destructive){detector.stop();detector.calibrationMode=false;CalibrationStore.shared.reset();detector.calibrationHits=0};Text("Audio is analysed on-device. Continuous recordings are not saved.").font(.caption).foregroundStyle(.secondary)}.padding().navigationTitle("Calibration")}}
 var history:some View{NavigationStack{List{ForEach(sessions){s in Section(s.startedAt.formatted(date:.abbreviated,time:.shortened)){HStack{Text("\(s.rallies.count) rallies");Spacer();Text("\(s.totalHits) hits");Spacer();Text("Best \(s.best)").bold()};ForEach(s.rallies.sorted{$0.startedAt<$1.startedAt}){r in HStack{Text(r.startedAt.formatted(date:.omitted,time:.standard));Spacer();Text("\(r.hits) hits").bold()}}}}}.navigationTitle("History").overlay{if sessions.isEmpty{ContentUnavailableView("No sessions yet",systemImage:"figure.pickleball",description:Text("Completed rallies appear here."))}}}}
}
